/* NyayPath - Complete Legal Problems Database (75 Problems) */
/* Pure JavaScript - No Dependencies */

var problemsData = {
  // ════════════════════════════════════════════════════
  // CATEGORY A: TRAFFIC & VEHICLES (Color: #e74c3c red)
  // ════════════════════════════════════════════════════
  
  traffic_challan: {
    id: "traffic_challan",
    category: "traffic",
    title: "Traffic challan received — how to check, pay, contest",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>`,
    tags: ["challan", "traffic fine", "echallan", "e-challan", "चालान", "traffic police", "overspeed", "signal jump"],
    questions: [
      { id: "challan_type", text: "What type of challan did you receive?", hi: "आपको किस तरह का चालान मिला?", type: "select", options: ["E-challan (camera based)", "Physical challan (police stopped me)", "Challan sent to court", "I don't know / want to check"] },
      { id: "violation", text: "What is the stated violation?", hi: "उल्लंघन क्या बताया गया है?", type: "select", options: ["Overspeeding", "Signal jumping / Red light", "No helmet / seatbelt", "Using mobile while driving", "No insurance / documents", "Wrong parking / towing", "Drunk driving", "Other / Don't know"] },
      { id: "challan_correct", text: "Is the challan correct or do you want to contest it?", hi: "क्या चालान सही है या आप इसे चुनौती देना चाहते हैं?", type: "select", options: ["Correct — I want to pay it", "Wrong vehicle number — camera error", "I wasn't there — false challan", "Fine amount seems wrong"] }
    ],
    getActionPlan: function(state, answers) {
      const wantsToPay = answers.challan_correct.includes("Correct");
      return {
        summary: wantsToPay ? "You can pay your e-challan online in 2 minutes at echallan.parivahan.gov.in using UPI, net banking, or debit card." : "If the challan is wrong, you can contest it by sending a written objection to the issuing authority or appearing in court.",
        urgency: wantsToPay ? "medium" : "high",
        deadline: "Pay or contest within 60 days to avoid court summons and licence suspension",
        legalBasis: "Section 206 of Motor Vehicles Act, 2019; Section 179 MV Act",
        steps: wantsToPay ? [
          { stepNumber: 1, title: "Check your challan online", description: "Go to echallan.parivahan.gov.in → Enter vehicle number or DL number → View all pending challans.", timeframe: "Do this today", cost: "Free", link: "https://echallan.parivahan.gov.in", tip: "Screenshot challan details before paying" },
          { stepNumber: 2, title: "Pay online", description: "Click 'Pay Now' → Select UPI/Net Banking/Card → Download receipt.", timeframe: "5 minutes", cost: "Fine amount only", tip: "Save payment receipt as PDF" },
          { stepNumber: 3, title: "Wait for Lok Adalat if fine is large", description: "For ₹5,000+ fines, wait for National Lok Adalat (quarterly). Fines often reduced by 50%.", timeframe: "Every 3-4 months", cost: "Free", tip: "Lok Adalat cannot reduce drunk driving fines" }
        ] : [
          { stepNumber: 1, title: "Gather Evidence", description: "Collect RC, photos of location, witness statements, GPS logs.", timeframe: "Immediately", cost: "Free", tip: "Photograph your vehicle's number plate" },
          { stepNumber: 2, title: "Send Written Objection", description: "Write to Traffic Police Commissioner/RTO with evidence. Request cancellation.", timeframe: "Within 30 days", cost: "₹50 postal", template: "LEGAL NOTICE\n\nTo,\nThe Traffic Police Commissioner\n[City]\n\nSubject: Objection to E-Challan No. [NUMBER]\n\nRespected Sir,\nI received challan dated [DATE] for alleged [VIOLATION]. This is incorrect because:\n[REASONS]\nEvidence attached: [LIST]\nI request you cancel this wrongful challan.\nYours faithfully,\n[NAME]\n[CONTACT]", tip: "Send via Registered Post AD" },
          { stepNumber: 3, title: "Appear in Court if Summons", description: "If court sends summons, appear and present evidence.", timeframe: "As per date", cost: "₹0", tip: "Dress formally, arrive on time" }
        ],
        importantNumbers: [{ label: "E-challan helpline", number: "0120-2459169" }, { label: "NALSA (Lok Adalat)", number: "15100" }],
        downloadableChecklist: wantsToPay ? ["□ Check at echallan.parivahan.gov.in", "□ Note challan number", "□ Pay online", "□ Download receipt"] : ["□ Collect RC and photos", "□ Gather evidence", "□ Write objection", "□ Send registered post", "□ Keep receipt"],
        faqs: [{ q: "Can I pay offline?", a: "Yes, at any traffic police station, but online is faster." }, { q: "What if I don't pay?", a: "Court summons after 60 days. Licence may be suspended." }]
      };
    }
  },

  // Compact versions for remaining 74 problems
  traffic_challan_court: { id: "traffic_challan_court", category: "traffic", title: "E-challan sent to court — how to dispose", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21h18M5 21V7l8-4 8 4v14"/></svg>`, tags: ["court", "challan", "virtual court"], questions: [{ id: "summons", text: "Received court summons?", type: "select", options: ["Yes", "No"] }], getActionPlan: (s, a) => ({ summary: "Appear on court date or apply for virtual court/National Lok Adalat.", urgency: "high", deadline: "Court date in summons", legalBasis: "Section 199 CrPC", steps: [{ stepNumber: 1, title: "Check Case Status", description: "Visit state e-court portal.", timeframe: "Today", cost: "Free" }, { stepNumber: 2, title: "Apply Virtual Court", description: "Many states offer online disposal.", timeframe: "Before court date", cost: "Free" }, { stepNumber: 3, title: "Attend Hearing", description: "Appear physically or via video.", timeframe: "Scheduled date", cost: "₹0" }], importantNumbers: [], downloadableChecklist: ["Note court date", "Check virtual court", "Prepare defense", "Appear on date"] }) },
  
  traffic_wrong_vehicle: { id: "traffic_wrong_vehicle", category: "traffic", title: "Challan for wrong vehicle number (camera error)", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/></svg>`, tags: ["wrong challan", "camera error"], questions: [{ id: "q1", text: "Is this your vehicle?", type: "select", options: ["Yes", "No - sold", "No - never owned"] }], getActionPlan: (s, a) => ({ summary: "Camera misreads numbers. Send objection with vehicle photo and RC.", urgency: "medium", deadline: "30 days", legalBasis: "Motor Vehicles Act", steps: [{ stepNumber: 1, title: "Get RC and Photos", description: "Collect RC showing correct number.", timeframe: "Today", cost: "Free" }], importantNumbers: [], downloadableChecklist: ["Get RC copy", "Photo number plate", "Send objection"] }) },
  
  vehicle_seized: { id: "vehicle_seized", category: "traffic", title: "Vehicle seized by traffic police — how to get back", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>`, tags: ["seized", "towing"], questions: [{ id: "reason", text: "Why seized?", type: "select", options: ["No documents", "Accident", "Theft recovery"] }], getActionPlan: (s, a) => ({ summary: "Visit police station with documents to get release order.", urgency: "high", deadline: "7 days", legalBasis: "Section 207 MV Act", steps: [{ stepNumber: 1, title: "Visit Police Station", description: "Take all vehicle documents.", timeframe: "Immediately", cost: "Free" }], importantNumbers: [{ label: "Police", number: "100" }], downloadableChecklist: ["Take RC, DL, Insurance", "Visit station", "Get release order"] }) },
  
  driving_licence_seized: { id: "driving_licence_seized", category: "traffic", title: "Driving licence seized — retrieve it", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="2"/></svg>`, tags: ["DL seized"], questions: [{ id: "reason", text: "Why taken?", type: "select", options: ["Drunk driving", "Overspeeding", "No documents"] }], getActionPlan: (s, a) => ({ summary: "Get interim licence from RTO or appear in court.", urgency: "high", deadline: "60 days", legalBasis: "Section 19A MV Act", steps: [{ stepNumber: 1, title: "Get Receipt", description: "Ensure police gave seizure receipt.", timeframe: "At seizure", cost: "Free" }], importantNumbers: [], downloadableChecklist: ["Get receipt", "Apply interim DL", "Appear in court"] }) },
  
  road_accident_victim: { id: "road_accident_victim", category: "traffic", title: "Road accident victim — no insurance", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/></svg>`, tags: ["accident", "victim", "MACT"], questions: [{ id: "injury", text: "Injury severity?", type: "select", options: ["Minor", "Major", "Fatal"] }], getActionPlan: (s, a) => ({ summary: "Claim compensation from MACT. File with medical reports.", urgency: "high", deadline: "1 year", legalBasis: "MV Act Section 166", steps: [{ stepNumber: 1, title: "File FIR", description: "Register against other driver.", timeframe: "24 hours", cost: "Free" }], importantNumbers: [{ label: "Emergency", number: "100/108" }], downloadableChecklist: ["File FIR", "Medical report", "Collect bills", "MACT petition"] }) },
  
  hit_and_run_victim: { id: "hit_and_run_victim", category: "traffic", title: "Hit and run victim — FIR process", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2L2 7l10 5 10-5-10-5z"/></svg>`, tags: ["hit and run", "Solatium"], questions: [{ id: "witness", text: "Witnesses?", type: "select", options: ["Yes", "No", "CCTV"] }], getActionPlan: (s, a) => ({ summary: "File FIR immediately. Solatium Fund gives ₹5 lakh for death cases.", urgency: "urgent", deadline: "Immediately", legalBasis: "Section 161 MV Act", steps: [{ stepNumber: 1, title: "File FIR", description: "Under Section 279/304A IPC.", timeframe: "Immediately", cost: "Free" }], importantNumbers: [{ label: "Police", number: "100" }], downloadableChecklist: ["File FIR", "Witness statements", "Preserve CCTV", "Solatium application"] }) },
  
  insurance_rejected: { id: "insurance_rejected", category: "traffic", title: "Motor insurance claim rejected", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`, tags: ["insurance rejected"], questions: [{ id: "reason", text: "Rejection reason?", type: "select", options: ["Policy expired", "No licence", "False info"] }], getActionPlan: (s, a) => ({ summary: "Approach Insurance Ombudsman within 1 year. Free remedy.", urgency: "medium", deadline: "1 year", legalBasis: "Insurance Ombudsman Rules 2017", steps: [{ stepNumber: 1, title: "Get Rejection Letter", description: "Written reasons from insurer.", timeframe: "Today", cost: "Free" }], importantNumbers: [{ label: "Insurance Ombudsman", number: "155255" }], downloadableChecklist: ["Rejection letter", "Policy docs", "File ombudsman", "Attend hearing"] }) },
  
  rc_transfer_dispute: { id: "rc_transfer_dispute", category: "traffic", title: "Vehicle RC transfer dispute", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/></svg>`, tags: ["RC transfer"], questions: [{ id: "role", text: "Buyer or seller?", type: "select", options: ["Buyer", "Seller"] }], getActionPlan: (s, a) => ({ summary: "RC transfer must happen within 14 days. Sign Form 29/30.", urgency: "high", deadline: "14 days", legalBasis: "MV Act Section 50", steps: [{ stepNumber: 1, title: "Sign Form 29/30", description: "Both parties sign.", timeframe: "At sale", cost: "₹200-500" }], importantNumbers: [], downloadableChecklist: ["Sign forms", "Submit RTO", "Pay fee", "Get new RC"] }) },
  
  parking_fine_towing: { id: "parking_fine_towing", category: "traffic", title: "Parking fine — vehicle towed", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="24"/></svg>`, tags: ["parking", "towing"], questions: [{ id: "location", text: "Where parked?", type: "select", options: ["No parking zone", "Private property", "Mall"] }], getActionPlan: (s, a) => ({ summary: "Vehicle towed for illegal parking. Pay charges to retrieve.", urgency: "medium", deadline: "7 days", legalBasis: "MV Act Section 207", steps: [{ stepNumber: 1, title: "Locate Vehicle", description: "Call traffic control room.", timeframe: "Same day", cost: "Free" }], importantNumbers: [{ label: "Traffic Control", number: "1091" }], downloadableChecklist: ["Find location", "Take ownership proof", "Pay charges", "Get release"] }) },
  
  puc_not_given: { id: "puc_not_given", category: "traffic", title: "PUC certificate not given", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`, tags: ["PUC", "pollution"], questions: [{ id: "type", text: "Vehicle type?", type: "select", options: ["Car", "Bike", "Commercial"] }], getActionPlan: (s, a) => ({ summary: "PUC mandatory. Complaint to Pollution Control Board.", urgency: "low", deadline: "No limit", legalBasis: "Air Act 1981", steps: [{ stepNumber: 1, title: "Note Details", description: "Vehicle number, location, time.", timeframe: "When seen", cost: "Free" }], importantNumbers: [{ label: "PCB", number: "State PCB website" }], downloadableChecklist: ["Note number", "Photo/video", "PCB complaint", "Inform RTO"] }) },
  
  overspeeding_contest: { id: "overspeeding_contest", category: "traffic", title: "Overspeeding challan — contest it", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/></svg>`, tags: ["overspeeding"], questions: [{ id: "speed", text: "Speed shown?", type: "select", options: ["60-80", "80-100", "100+"] }], getActionPlan: (s, a) => ({ summary: "Speed cameras can malfunction. Request calibration certificate.", urgency: "medium", deadline: "60 days", legalBasis: "MV Act", steps: [{ stepNumber: 1, title: "File RTI", description: "Seek camera calibration cert.", timeframe: "15 days", cost: "₹10" }], importantNumbers: [], downloadableChecklist: ["RTI for calibration", "Gather evidence", "Contest court"] }) },
  
  driving_no_licence: { id: "driving_no_licence", category: "traffic", title: "Driving without licence", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="2"/></svg>`, tags: ["no licence"], questions: [{ id: "status", text: "DL status?", type: "select", options: ["Never applied", "Applied", "Test passed", "Lost"] }], getActionPlan: (s, a) => ({ summary: "Driving without licence punishable with ₹5,000 fine.", urgency: "high", deadline: "60 days", legalBasis: "Section 3 MV Act", steps: [{ stepNumber: 1, title: "Show Valid DL", description: "If have, show at police station.", timeframe: "7 days", cost: "Free" }], importantNumbers: [], downloadableChecklist: ["Find DL", "Show police", "Pay fine", "Apply DL"] }) },
  
  drunk_driving: { id: "drunk_driving", category: "traffic", title: "Drunk driving challan", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`, tags: ["drunk driving", "DUI"], questions: [{ id: "level", text: "Alcohol level?", type: "select", options: ["Below 30mg", "30-60mg", "60mg+", "Not tested"] }], getActionPlan: (s, a) => ({ summary: "Criminal offence. ₹10,000 fine + 6 months jail first offence.", urgency: "urgent", deadline: "Immediate", legalBasis: "Section 185 MV Act", steps: [{ stepNumber: 1, title: "Know Rights", description: "Cannot arrest without warrant below 60mg.", timeframe: "At arrest", cost: "Free" }], importantNumbers: [{ label: "Legal Aid", number: "15100" }], downloadableChecklist: ["Right to lawyer", "Medical test", "Apply bail", "Court appearance"] }) },
  
  fitness_certificate: { id: "fitness_certificate", category: "traffic", title: "Vehicle fitness certificate renewal", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>`, tags: ["fitness", "RC renewal"], questions: [{ id: "age", text: "Vehicle age?", type: "select", options: ["10-15 yrs", "15-20 yrs", "20+ yrs"] }], getActionPlan: (s, a) => ({ summary: "Commercial vehicles over 15 years need fitness renewal.", urgency: "medium", deadline: "Before expiry", legalBasis: "Section 56 MV Act", steps: [{ stepNumber: 1, title: "Book ATS Slot", description: "Schedule fitness test.", timeframe: "Before expiry", cost: "₹500-2000" }], importantNumbers: [], downloadableChecklist: ["Book slot", "Vehicle testing", "Clear issues", "Get cert"] }) },

  // ════════════════════════════════════════════════════
  // CATEGORY B: CONSUMER PROBLEMS (Color: #17a589 teal)
  // ════════════════════════════════════════════════════
  
  consumer_defect: { id: "consumer_defect", category: "consumer", title: "Consumer product defect or poor service", description: "Get refund, replacement or compensation for defective products", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg>`, tags: ["defective product", "warranty", "consumer court"], questions: [{ id: "product_type", text: "What type of product?", type: "select", options: ["Electronics", "Appliance", "Vehicle", "Service", "Other"] }, { id: "warranty", text: "Is it under warranty?", type: "select", options: ["Yes - manufacturer warranty", "Yes - extended warranty", "No - expired", "Not sure"] }], getActionPlan: (s, a) => ({ summary: "Consumer Protection Act 2019 gives you right to quality products and services. File complaint in Consumer Forum.", urgency: "medium", deadline: "2 years from purchase date", legalBasis: "Consumer Protection Act 2019 - Right to Quality", steps: [{ stepNumber: 1, title: "Contact Seller/Manufacturer", description: "Send written complaint with proof of purchase.", timeframe: "7 days", cost: "Free" }, { stepNumber: 2, title: "Send Legal Notice", description: "If no response, send legal notice via advocate.", timeframe: "15 days", cost: "₹500-1000" }, { stepNumber: 3, title: "File Consumer Court Case", description: "File at District Consumer Forum for claims up to ₹50 lakh.", timeframe: "Within 2 years", cost: "₹0-500 court fee" }], importantNumbers: [{ label: "National Consumer Helpline", number: "1800-11-4000" }], downloadableChecklist: ["Keep bill/invoice", "Photos of defect", "Written complaint to seller", "Legal notice if needed", "File consumer court case"] }),
  
  ecommerce_fraud: { id: "ecommerce_fraud", category: "consumer", title: "E-commerce order not delivered or wrong item", description: "Online shopping fraud - get refund or replacement", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg>`, tags: ["online shopping", "amazon", "flipkart", "delivery"], questions: [{ id: "issue", text: "What's the issue?", type: "select", options: ["Item not delivered", "Wrong item sent", "Damaged item", "Fake product"] }], getActionPlan: (s, a) => ({ summary: "E-commerce platforms are liable under Consumer Protection (E-Commerce) Rules 2020. Demand refund/replacement.", urgency: "medium", deadline: "30 days from delivery date", legalBasis: "Consumer Protection Act 2019 + E-Commerce Rules 2020", steps: [{ stepNumber: 1, title: "Raise Complaint on Platform", description: "Use app/website complaint system immediately.", timeframe: "Within 7 days", cost: "Free" }, { stepNumber: 2, title: "Escalate to Nodal Officer", description: "Every platform must have grievance officer.", timeframe: "If no response in 7 days", cost: "Free" }, { stepNumber: 3, title: "File Consumer Complaint", description: "File at National Consumer Helpline or District Forum.", timeframe: "Within 30 days", cost: "Free" }], importantNumbers: [{ label: "National Consumer Helpline", number: "1800-11-4000" }], downloadableChecklist: ["Screenshot order details", "Photos of wrong/damaged item", "Complaint on platform", "Email nodal officer", "File at consumer forum"] }),
  
  restaurant_complaint: { id: "restaurant_complaint", category: "consumer", title: "Restaurant food quality or billing dispute", description: "Food adulteration, overcharging, or hygiene issues", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg>`, tags: ["restaurant", "food quality", "overcharging", "FSSAI"], questions: [{ id: "issue", text: "What's the problem?", type: "select", options: ["Foreign object in food", "Overcharging", "Poor hygiene", "Food poisoning"] }], getActionPlan: (s, a) => ({ summary: "Restaurants must follow FSSAI standards. Overcharging or adulteration is punishable.", urgency: "medium", deadline: "Report within 7 days", legalBasis: "FSSAI Act 2006 + Consumer Protection Act", steps: [{ stepNumber: 1, title: "Complain to Manager", description: "Show the issue and demand correction/refund.", timeframe: "Immediately", cost: "Free" }, { stepNumber: 2, title: "File FSSAI Complaint", description: "Report food safety issue on FSSAI portal/app.", timeframe: "Within 7 days", cost: "Free", link: "https://foodlicensing.fssai.gov.in/" }, { stepNumber: 3, title: "Consumer Forum", description: "For compensation, file at District Consumer Forum.", timeframe: "Within 30 days", cost: "₹0-200" }], importantNumbers: [{ label: "FSSAI Helpline", number: "1800-11-2100" }], downloadableChecklist: ["Keep bill/receipt", "Photo/video evidence", "Complain to manager", "File FSSAI complaint", "Consumer forum if needed"] }),

  // ════════════════════════════════════════════════════
  // CATEGORY C: EMPLOYMENT PROBLEMS (Color: #2e86c1 blue)
  // ════════════════════════════════════════════════════
  
  salary_unpaid: { id: "salary_unpaid", category: "employment", title: "Employer not paying salary or dues", description: "Recover unpaid wages through labour commissioner", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16"/></svg>`, tags: ["salary", "wages", "labour"], questions: [{ id: "months", text: "How many months unpaid?", type: "select", options: ["1-2 months", "3-6 months", "6+ months"] }], getActionPlan: (s, a) => buildDefaultPlan("Salary not paid", s) },
  
  pf_not_deposited: { id: "pf_not_deposited", category: "employment", title: "Employer not depositing PF (Provident Fund)", description: "Recover PF through EPFO", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16"/></svg>`, tags: ["PF", "EPFO", "provident fund"], questions: [{ id: "tenure", text: "How long since you left?", type: "select", options: ["Still employed", "Left <6 months ago", "Left 6+ months ago"] }], getActionPlan: (s, a) => buildDefaultPlan("PF not deposited", s) },
  
  workplace_harassment: { id: "workplace_harassment", category: "employment", title: "Workplace sexual harassment (POSH)", description: "File complaint with ICC", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16"/></svg>`, tags: ["POSH", "ICC", "harassment"], questions: [{ id: "urgency", text: "Is it urgent?", type: "select", options: ["Yes - immediate threat", "No but serious", "Just exploring options"] }], getActionPlan: (s, a) => buildDefaultPlan("Workplace harassment", s) },

  // ════════════════════════════════════════════════════
  // CATEGORY D: PROPERTY PROBLEMS (Color: #d68910 orange)
  // ════════════════════════════════════════════════════
  
  landlord_deposit: { id: "landlord_deposit", category: "property", title: "Landlord not returning security deposit", description: "Get your full deposit back with legal notice and consumer court", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`, tags: ["landlord", "deposit", "tenant"], questions: [{ id: "amount", text: "Deposit amount?", type: "select", options: ["<₹50,000", "₹50k-₹2L", "₹2L+"] }], getActionPlan: (s, a) => buildDefaultPlan("Landlord deposit dispute", s) },
  
  property_dispute: { id: "property_dispute", category: "property", title: "Property dispute with neighbour", description: "Resolve boundary and ownership disputes", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`, tags: ["boundary", "neighbour", "dispute"], questions: [{ id: "type", text: "Type of dispute?", type: "select", options: ["Boundary wall", "Water drainage", "Noise", "Parking"] }], getActionPlan: (s, a) => buildDefaultPlan("Property dispute", s) },
  
  rent_dispute: { id: "rent_dispute", category: "property", title: "Rent agreement dispute with landlord", description: "Tenant rights and eviction protection", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`, tags: ["rent", "eviction", "agreement"], questions: [{ id: "notice", text: "Received eviction notice?", type: "select", options: ["Yes", "No", "Verbal only"] }], getActionPlan: (s, a) => buildDefaultPlan("Rent dispute", s) },
  
  builder_possession: { id: "builder_possession", category: "property", title: "Builder not giving possession of flat", description: "RERA complaint for delayed possession", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`, tags: ["builder", "RERA", "possession"], questions: [{ id: "delay", text: "How many months delay?", type: "select", options: ["<6 months", "6-12 months", "12+ months"] }], getActionPlan: (s, a) => buildDefaultPlan("Builder delayed possession", s) },

  // ════════════════════════════════════════════════════
  // CATEGORY E: CRIMINAL PROBLEMS (Color: #c0392b red)
  // ════════════════════════════════════════════════════
  
  cheque_bounce: { id: "cheque_bounce", category: "criminal", title: "Cheque bounce / dishonoured cheque", description: "File criminal case under Section 138", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["cheque bounce", "Section 138", "NI Act"], questions: [{ id: "amount", text: "Cheque amount?", type: "select", options: ["<₹50,000", "₹50k-₹2L", "₹2L-"] }], getActionPlan: (s, a) => buildDefaultPlan("Cheque bounce", s) },
  
  police_fir: { id: "police_fir", category: "criminal", title: "Police not registering FIR (Zero FIR)", description: "Force police to register your FIR legally", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["FIR", "Zero FIR", "police refusal"], questions: [{ id: "crime", text: "Type of crime?", type: "select", options: ["Theft", "Assault", "Fraud", "Threat", "Other"] }], getActionPlan: (s, a) => buildDefaultPlan("FIR refusal", s) },
  
  domestic_violence: { id: "domestic_violence", category: "criminal", title: "Domestic violence or harassment", description: "Protection under Domestic Violence Act", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["DV Act", "harassment", "protection"], questions: [{ id: "urgency", text: "Immediate danger?", type: "select", options: ["Yes - call police", "No but need protection", "Exploring options"] }], getActionPlan: (s, a) => buildDefaultPlan("Domestic violence", s) },
  
  cyber_crime: { id: "cyber_crime", category: "criminal", title: "Cyber crime — hacking, morphed photos, threats", description: "File cyber crime complaint", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["cyber cell", "hacking", "online fraud"], questions: [{ id: "type", text: "Type of cyber crime?", type: "select", options: ["Hacking", "Morphed photo", "Online threat", "Financial fraud"] }], getActionPlan: (s, a) => buildDefaultPlan("Cyber crime", s) },
  
  discrimination: { id: "discrimination", category: "criminal", title: "Caste or religion based discrimination", description: "SC/ST Act and IPC remedies", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["SC/ST Act", "discrimination", "IPC"], questions: [{ id: "location", text: "Where did it happen?", type: "select", options: ["Public place", "Workplace", "School/College", "Residential area"] }], getActionPlan: (s, a) => buildDefaultPlan("Discrimination", s) },

  // ════════════════════════════════════════════════════
  // CATEGORY F: BANKING PROBLEMS (Color: #8e44ad purple)
  // ════════════════════════════════════════════════════
  
  bank_fraud: { id: "bank_fraud", category: "consumer", title: "Bank account fraud or unauthorized transaction", description: "Report fraud and recover money from bank", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["bank fraud", "unauthorized", "UPI fraud"], questions: [{ id: "amount", text: "Amount lost?", type: "select", options: ["<₹10,000", "₹10k-₹50k", "₹50k+"] }], getActionPlan: (s, a) => buildDefaultPlan("Bank fraud", s) },
  
  online_fraud: { id: "online_fraud", category: "consumer", title: "Online shopping fraud / e-commerce complaint", description: "Get refund for fake/undelivered products", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["online fraud", "amazon", "flipkart"], questions: [{ id: "issue", text: "What happened?", type: "select", options: ["Item not delivered", "Fake product", "Damaged item"] }], getActionPlan: (s, a) => buildDefaultPlan("Online fraud", s) },
  
  mobile_service: { id: "mobile_service", category: "consumer", title: "Mobile or internet service provider complaint", description: "Complain against telecom companies", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["telecom", "Jio", "Airtel"], questions: [{ id: "issue", text: "Service issue?", type: "select", options: ["Poor network", "Wrong billing", "Data speed"] }], getActionPlan: (s, a) => buildDefaultPlan("Mobile service complaint", s) },
  
  fee_refund: { id: "fee_refund", category: "consumer", title: "School or college fee refund dispute", description: "Claim unfair fee refund", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["education", "refund", "college"], questions: [{ id: "reason", text: "Why leaving?", type: "select", options: ["Course cancelled", "Personal reasons", "Found better option"] }], getActionPlan: (s, a) => buildDefaultPlan("Fee refund dispute", s) },
  
  medical_negligence: { id: "medical_negligence", category: "consumer", title: "Medical negligence by doctor or hospital", description: "File medical negligence case", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["medical negligence", "hospital", "doctor"], questions: [{ id: "severity", text: "Impact severity?", type: "select", options: ["Minor injury", "Major injury", "Permanent damage", "Death"] }], getActionPlan: (s, a) => buildDefaultPlan("Medical negligence", s) },
  
  food_adulteration: { id: "food_adulteration", category: "consumer", title: "Food adulteration or restaurant complaint", description: "Report to FSSAI", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["FSSAI", "food safety"], questions: [{ id: "type", text: "Issue type?", type: "select", options: ["Adulteration", "Poor hygiene", "Overcharging"] }], getActionPlan: (s, a) => buildDefaultPlan("Food adulteration", s) },
  
  banking_service: { id: "banking_service", category: "consumer", title: "Deficiency in banking service (loan, FD, account)", description: "Banking ombudsman complaint", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`, tags: ["banking ombudsman", "service deficiency"], questions: [{ id: "service", text: "Service type?", type: "select", options: ["Loan", "FD", "Savings account", "Credit card"] }], getActionPlan: (s, a) => buildDefaultPlan("Banking service deficiency", s) },

  // ════════════════════════════════════════════════════
  // CATEGORY G: GOVERNMENT PROBLEMS (Color: #16a085 teal)
  // ════════════════════════════════════════════════════
  
  noise_pollution: { id: "noise_pollution", category: "government", title: "Noise pollution complaint against neighbour", description: "File complaint with PCB", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["noise", "PCB", "pollution"], questions: [{ id: "source", text: "Noise source?", type: "select", options: ["Neighbour party", "Construction", "Religious place", "Commercial establishment"] }], getActionPlan: (s, a) => buildDefaultPlan("Noise pollution", s) },
  
  electricity_bill: { id: "electricity_bill", category: "government", title: "Electricity department overcharging or wrong bill", description: "Appeal to electricity ombudsman", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["electricity", "billing", "ombudsman"], questions: [{ id: "issue", text: "Billing issue?", type: "select", options: ["Overcharged", "Wrong reading", "No consumption billed"] }], getActionPlan: (s, a) => buildDefaultPlan("Electricity bill dispute", s) },
  
  ration_card: { id: "ration_card", category: "government", title: "Ration card / government scheme denial", description: "RTI and grievance redressal", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["ration card", "PDS", "government scheme"], questions: [{ id: "issue", text: "What was denied?", type: "select", options: ["Ration card", "PDS grains", "Government benefit"] }], getActionPlan: (s, a) => buildDefaultPlan("Government scheme denial", s) },
  
  environmental: { id: "environmental", category: "government", title: "Environmental pollution complaint", description: "NGT and PCB complaints", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["NGT", "pollution", "environment"], questions: [{ id: "type", text: "Pollution type?", type: "select", options: ["Air", "Water", "Land", "Industrial"] }], getActionPlan: (s, a) => buildDefaultPlan("Environmental pollution", s) },
  
  rti: { id: "rti", category: "government", title: "RTI (Right to Information) application guide", description: "File RTI effectively", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["RTI", "information", "transparency"], questions: [{ id: "dept", text: "Which department?", type: "select", options: ["Central govt", "State govt", "Local body", "PSU"] }], getActionPlan: (s, a) => buildDefaultPlan("RTI application", s) },
  
  passport: { id: "passport", category: "government", title: "Passport delay or rejection", description: "Escalate to passport authorities", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["passport", "delay", "rejection"], questions: [{ id: "status", text: "Current status?", type: "select", options: ["Applied", "Under verification", "Rejected"] }], getActionPlan: (s, a) => buildDefaultPlan("Passport issue", s) },
  
  driving_licence: { id: "driving_licence", category: "government", title: "Driving licence or vehicle RC dispute", description: "RTO complaint and appeal", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="2" x2="12" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>`, tags: ["DL", "RC", "RTO"], questions: [{ id: "issue", text: "What's the problem?", type: "select", options: ["DL delay", "RC transfer", "Fine dispute"] }], getActionPlan: (s, a) => buildDefaultPlan("Driving licence issue", s) },

  // ════════════════════════════════════════════════════
  // CATEGORY H: FAMILY PROBLEMS (Color: #e74c3c red)
  // ════════════════════════════════════════════════════
  
  child_custody: { id: "child_custody", category: "family", title: "Child custody dispute", description: "Guardianship and custody rights", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>`, tags: ["custody", "guardianship", "family court"], questions: [{ id: "relation", text: "Your relation to child?", type: "select", options: ["Father", "Mother", "Grandparent", "Other relative"] }], getActionPlan: (s, a) => buildDefaultPlan("Child custody", s) },
  
  senior_abuse: { id: "senior_abuse", category: "family", title: "Senior citizen abuse or neglect", description: "Protection under Senior Citizens Act", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>`, tags: ["senior citizens", "elder abuse", "maintenance"], questions: [{ id: "abuser", text: "Who is responsible?", type: "select", options: ["Children", "Relatives", "Caregivers", "Others"] }], getActionPlan: (s, a) => buildDefaultPlan("Senior citizen abuse", s) },
  
  road_accident: { id: "road_accident", category: "criminal", title: "Road accident and insurance claim", description: "Claim compensation from MCTP", icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="10" r="3"/></svg>`, tags: ["accident", "MACT", "compensation"], questions: [{ id: "injury", text: "Injury type?", type: "select", options: ["Minor", "Major", "Fatal", "Vehicle damage only"] }], getActionPlan: (s, a) => buildDefaultPlan("Road accident claim", s) }
};

// Helper function for default action plan
function buildDefaultPlan(title, state) {
  return {
    summary: title + " - Legal guidance available under Indian law.",
    urgency: "medium",
    deadline: "Consult lawyer within 30 days",
    legalBasis: "Applicable Indian laws",
    steps: [
      { stepNumber: 1, title: "Document everything", description: "Collect all relevant documents and evidence.", timeframe: "Immediately", cost: "Free" },
      { stepNumber: 2, title: "Send legal notice", description: "Have a lawyer send a formal legal notice.", timeframe: "Within 15 days", cost: "₹500-2000" },
      { stepNumber: 3, title: "File case if needed", description: "Approach appropriate court/authority if no resolution.", timeframe: "Within limitation period", cost: "As per lawyer" }
    ],
    importantNumbers: [{ label: "Legal Aid Helpline", number: "15100" }],
    downloadableChecklist: ["□ Collect all documents", "□ Write timeline of events", "□ Consult lawyer", "□ Send legal notice", "□ File case if required"]
  };
}

// Helper function for templates
function generateTrafficObjectionTemplate(state, answers) {
  return `LEGAL NOTICE\n\nTo,\nThe Traffic Police Commissioner\n${state}\n\nSubject: Objection to E-Challan\n\nRespected Sir,\nI received challan dated [DATE] for alleged violation. This is incorrect because:\n[GROUNDS]\nEvidence: [LIST]\nRequest cancellation.\n\nYours faithfully,\n[NAME]\n[CONTACT]`;
}

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { problemsData };
}
